import { useEffect, useState } from 'react'
import { request } from '../request'
import './proof-page.css'
type Proof = { id: string; image_id: string; proof_hash: string; public_inputs_hash: string; proof_profile: string; receipt_size: number; public_statement: Record<string, unknown> }
type Market = { symbol: string; interval: string; source: string; period_start: number; period_end: number; bar_count: number; trust_model: string }
type Verified = { market?: Market; program?: { source: string; source_sha256: string; commission_bps: number; slippage_bps: number; compiled_program_commitment_verified: boolean } | null; reports?: { report_id: string; published_return_verified: boolean }[]; valid: boolean; image_id: string; proof_hash: string; journal: Record<string, unknown>; verification_seconds: number; verified_at: string }
const repository = 'https://github.com/ashcinder/atlas-quant-lab/blob/7e38e0930690de8952f1fb2e3f6004321c717907'
export default function ProofPage({ proofId }: { proofId: string }) {
  const [proof, setProof] = useState<Proof | null>(null), [verification, setVerification] = useState<Verified | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  useEffect(() => { if (!proofId) return; const abort = new AbortController(); request<Proof>(`/quantjudge/zk-proofs/${encodeURIComponent(proofId)}`, { signal: abort.signal }).then(setProof).catch(cause => { if (!abort.signal.aborted) setError(cause.message) }); return () => abort.abort() }, [proofId])
  async function verify() { if (busy || !proof) return; setBusy(true); setError(''); setVerification(null); try { const value = await request<Verified>(`/quantjudge/zk-proofs/${proof.id}/verify`, { method: 'POST' }); if (value.valid !== true || value.image_id !== proof.image_id || value.proof_hash !== proof.proof_hash) throw new Error('证明核验响应不一致'); setVerification(value) } catch (cause) { setError(cause instanceof Error ? cause.message : '验证失败') } finally { setBusy(false) } }
  const statement = (verification?.journal ?? proof?.public_statement) as { metrics?: { total_return_ppm: number }; period_start?: number; period_end?: number; market_data_hash?: string; initial_equity_micros?: number; final_equity_micros?: number } | undefined
  const date = (value?: number) => value ? new Date(value * 1000).toISOString().replace('T', ' ').slice(0, 19) + ' UTC' : '—'
  const apiRoot = (import.meta.env.VITE_API_ROOT ?? '/api/v1').replace(/\/$/, '')
  return <main className="proof-page"><a href="#quantjudge">← 返回策略市场</a><header><small>ATLAS · VERIFIABLE COMPUTATION</small><h1>ZKP / zkVM 证明验证</h1><p>zkVM 执行固定版本的回测程序，并生成零知识证明。验证者检查程序 ID 与公开结果，无需获取策略私有参数。</p></header>
    <ol className="proof-stages"><li>策略承诺</li><li>历史数据哈希</li><li>zkVM 执行</li><li>Receipt 验证</li></ol>
    {!proofId && <p>此策略尚未关联可核验的零知识证明。普通收益展示与哈希上链不会自动获得 ZKP 状态。</p>}
    {proof && <section><h2>{verification ? '本次密码学验证通过' : '证明已登记 · 等待本次验证'}</h2><button disabled={busy} onClick={() => void verify()}>{busy ? '真实验证中…' : '验证 Proof'}</button>{verification && <><p role="status">耗时 {verification.verification_seconds} 秒 · {verification.verified_at}</p><p><strong>{verification.market?.symbol} · 区间总收益 {statement?.metrics ? (statement.metrics.total_return_ppm / 10000).toFixed(4) + '%' : '—'}</strong></p><p>{date(statement?.period_start)} — {date(statement?.period_end)}</p></>}<dl>{[['Proof ID', proof.id], ['程序 Image ID', proof.image_id], ['Receipt SHA-256', proof.proof_hash], ['公开输入哈希', proof.public_inputs_hash], ['协议', proof.proof_profile], ['证明大小', `${proof.receipt_size} bytes`]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><a href={`${apiRoot}/quantjudge/zk-proofs/${proof.id}/receipt`}>下载原始 receipt</a><p><a href={`${apiRoot}/quantjudge/zk-proofs/${proof.id}/bundle`}>下载离线验证包（Proof、数据与独立验证脚本）</a></p><details><summary>公开 Journal（策略承诺、数据根、成本、收益与曲线）</summary><pre>{JSON.stringify(verification?.journal ?? proof.public_statement, null, 2)}</pre></details><h3>在自己的设备独立验证</h3><pre>{`strategy/zkvm/target/release/atlas-zkvm verify --receipt ${proof.id}.r0 --expected-image-id ${proof.image_id}`}</pre></section>}
    {verification && <section><h2>收益与输入绑定检查</h2><p>证明内区间总收益：<strong>{statement?.metrics ? (statement.metrics.total_return_ppm / 10000).toFixed(4) + '%' : '—'}</strong></p><p>市场公开报告：{verification.reports?.length ? verification.reports.every(report => report.published_return_verified) ? '已逐项核对，与证明输出一致' : '不一致' : '此证明尚未发布报告'}</p><p>标的：{verification.market?.symbol} · {verification.market?.interval} · {verification.market?.bar_count} 根 K 线 · {verification.market?.source}</p><p>区间：{date(statement?.period_start)} — {date(statement?.period_end)}</p><p>初始资金：{Number(statement?.initial_equity_micros) / 1000000} · 最终资金：{Number(statement?.final_equity_micros) / 1000000}（标的计价货币）</p>{statement?.market_data_hash && <><a href={`${apiRoot}/quantjudge/zkp/market-datasets/${statement.market_data_hash}`} download="market.json">下载绑定的完整历史 K 线</a><ProofCandles marketHash={statement.market_data_hash} /></>}{verification.program ? <><p>手续费：{verification.program.commission_bps / 100}% · 滑点：{verification.program.slippage_bps / 100}% · 信号收盘确认，下一根开盘执行</p><h3>公开测试策略代码 · 编译后承诺已核对</h3><a href={`${apiRoot}/quantjudge/zk-proofs/${proofId}/public-example`} download="public-example.json">下载公开测试源码与完整输入</a><pre>{verification.program.source}</pre><small>源码 SHA-256：{verification.program.source_sha256}</small><p>本例公开源码，独立重新编译并对照已证明的程序承诺。编译器在 zkVM 外运行；证明本体绑定的是编译后的整数程序。</p></> : <p>策略程序由公开承诺绑定；作者未公开源码，不展示未经绑定的代码。</p>}</section>}
    {error && <p role="alert">{error}</p>}
    <section><h2>开源验证程序</h2><p><a href={`${repository}/strategy/zkvm/host/src/main.rs`} target="_blank" rel="noreferrer">GitHub · Receipt 验证器</a> · <a href={`${repository}/strategy/zkvm/program-core/src/lib.rs`} target="_blank" rel="noreferrer">GitHub · v2 回测程序</a> · <a href={`${repository}/strategy/zkvm/profiles.json`} target="_blank" rel="noreferrer">固定程序 ID</a></p><p>下载源码后，按仓库 ZKP 文档构建本地工具；核对固定 Image ID，再验证 receipt。平台上“已登记”的状态不替代本次密码学核验。</p></section>
    <section><h2>证明的含义</h2><p>证明固定有界整数程序在承诺的历史数据上执行，以及该执行语义下的扣费收益。当前 Python 入口仅编译支持的子集；普通 Python 回测、外部 AI 响应、实盘成交与行情来源真实性不在该证明范围内。</p><p>本页仅核验 receipt，不宣称已完成链上合约验证。私有输入由生成证明的设备持有；在平台普通服务器上生成证明不能对服务器管理员隐藏输入。</p></section>
  </main>
}

function ProofCandles({ marketHash }: { marketHash: string }) {
  type Bar = { time: number; open_micros: number; high_micros: number; low_micros: number; close_micros: number }
  const [bars, setBars] = useState<Bar[]>([]), [error, setError] = useState('')
  useEffect(() => { const abort = new AbortController(); request<{ dataset: { bars: Bar[] } }>(`/quantjudge/zkp/market-datasets/${marketHash}`, { signal: abort.signal }).then(value => setBars(value.dataset.bars)).catch(cause => { if (!abort.signal.aborted) setError(cause.message) }); return () => abort.abort() }, [marketHash])
  if (error) return <p role="alert">历史图读取失败：{error}</p>
  if (!bars.length) return <p>读取绑定历史 K 线…</p>
  const shown = bars.length > 300 ? bars.filter((_, i) => i % Math.ceil(bars.length / 300) === 0) : bars
  const low = Math.min(...shown.map(b => b.low_micros)), high = Math.max(...shown.map(b => b.high_micros))
  const y = (price: number) => 180 - (price - low) / Math.max(1, high - low) * 160
  const width = 740 / shown.length
  return <figure><svg viewBox="0 0 800 210" role="img" aria-label="证明绑定的历史K线"><text x="2" y="14" fill="currentColor" fontSize="11">{(high / 1e6).toFixed(2)}</text><text x="2" y="185" fill="currentColor" fontSize="11">{(low / 1e6).toFixed(2)}</text>{shown.map((bar, i) => { const x = 55 + (i + .5) * width, color = bar.close_micros >= bar.open_micros ? '#12866c' : '#d7465b'; return <g key={bar.time}><title>{new Date(bar.time * 1000).toISOString()} 开 {bar.open_micros / 1e6} 收 {bar.close_micros / 1e6}</title><line x1={x} x2={x} y1={y(bar.high_micros)} y2={y(bar.low_micros)} stroke={color} /><rect x={x - width * .3} width={width * .6} y={Math.min(y(bar.open_micros), y(bar.close_micros))} height={Math.max(1, Math.abs(y(bar.close_micros) - y(bar.open_micros)))} fill={color} /></g> })}</svg><figcaption>{bars.length} 根绑定 K 线{bars.length > 300 ? '（图表抽样显示，下载包含完整数据）' : ''} · 悬停查看开收价格</figcaption></figure>
}
