import { useEffect, useState } from 'react'
import { request } from '../request'
import { WALLET_EVENT, walletAddress } from '../supervisorWallet'
export function SupervisorStatusButton({ expanded=false }: {expanded?:boolean}) {
 const [balance,setBalance]=useState<string|null>(null),[connected,setConnected]=useState(false),[address,setAddress]=useState(walletAddress),[busy,setBusy]=useState(false),[error,setError]=useState(''),[network,setNetwork]=useState('Supervisor')
 async function refresh(){setBusy(true);setError('');const a=walletAddress();setAddress(a);try{if(a){const value=await request<{balance_bkc:string;network_label?:string}>(`/wallet/balance?address=${encodeURIComponent(a)}`);setBalance(value.balance_bkc);setNetwork(value.network_label||'Supervisor');setConnected(true)}else{const s=await request<{connected:boolean}>('/quantjudge/chain/status');setConnected(s.connected);setBalance(null)}}catch(cause){setBalance(null);setError(cause instanceof Error?cause.message:'余额查询失败');try{const status=await request<{connected:boolean}>('/quantjudge/chain/status');setConnected(status.connected)}catch{setConnected(false)}}finally{setBusy(false)}}
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),30000);const listener=()=>void refresh();window.addEventListener(WALLET_EVENT,listener);return()=>{clearInterval(timer);window.removeEventListener(WALLET_EVENT,listener)}},[])
 return <button className={`supervisor-direct ${connected?'is-connected':''} ${expanded?'is-balance-card':''}`} onClick={()=>void refresh()} disabled={busy} title={error||`${network} · ${address||'请设置账户'}`} ><i/><span><small>{network}</small>{expanded&&<small>Supervisor 链上资产</small>}<strong>{balance!==null?`${Number(balance).toLocaleString('en-US',{maximumFractionDigits:6})} BKC`:connected?(address?'节点在线 · 余额待查':'BKC · 未配置账户'):'Supervisor · 未连接'}</strong>{expanded&&<small>{address?`${address.slice(0,8)}…${address.slice(-6)}`:'设置账户后显示链上余额'}</small>}</span></button>
}
